package_name_map:
  debian:
    bat: batcat
    fd: fd-find
  archlinux:
    signal: signal-desktop
  darwin:
    ttf-jetbrains-mono-nerd: font-jetbrains-mono-nerd-font
    aws-cli: awscli
    google-cloud-cli: google-cloud-sdk
