personal_apps:
  archlinux:
    - bitwarden-cli
  archlinux_aur:
    - zen-browser-bin
  flatpak:
    - md.obsidian.Obsidian
    - org.signal.Signal
    - org.videolan.VLC
    - com.discordapp.Discord
  darwin:
    - obsidian
    - signal
    - vlc
    - bitwarden-cli
    - discord

work_apps:
  archlinux: []
  archlinux_aur: []
  flatpak: []
  darwin: []

packages: "{{ personal_apps }}"
