all:
  children:
    personal:
      hosts:
        icewind:
    work:
      hosts:
        mithril:
    vm:
      hosts: {}
    desktop:
      children:
        personal:
        work:
    cli:
      children:
        desktop:
        vm:
    dev_go:
      children:
        personal:
        work:
