packages:
  archlinux:
    - github-cli
    - kubectl
    - k9s
    - aws-cli
    - azure-cli
    - terraform
    - opentofu
  archlinux_aur: {}
  darwin:
    - gh
    - kubectl
    - k9s
    - awscli
    - azure-cli
    - terraform
    - opentofu
    - google-cloud-sdk
