- name: Clone TPM (Tmux Plugin Manager)
  ansible.builtin.git:
    repo: https://github.com/tmux-plugins/tpm
    dest: "{{ ansible_facts['user_dir'] }}/.tmux/plugins/tpm"
    depth: 1
    update: true

- name: Deploy tmux config
  ansible.builtin.copy:
    src: tmux.conf
    dest: "{{ ansible_facts['user_dir'] }}/.tmux.conf"
    mode: "0644"
