- name: Gather facts
  ansible.builtin.setup:
  tags:
    - always

- name: Enable time synchronization (systemd)
  become: true
  ansible.builtin.systemd:
    name: systemd-timesyncd
    enabled: true
    state: started
  when: ansible_facts['system'] == "Linux"

- name: Set timezone (optional default)
  become: true
  community.general.timezone:
    name: "{{ system_timezone }}"
  when:
    - ansible_facts['system'] == "Linux"
    - system_timezone | length > 0

- name: Update packages
  ansible.builtin.include_tasks:
    file: "update/{{ ansible_facts['distribution'] }}.yml"
  tags:
    - update

- name: Install packages
  ansible.builtin.include_tasks:
    file: "install/{{ ansible_facts['distribution'] }}.yml"
  tags:
    - packages
