- name: Gather facts
  ansible.builtin.setup:
  tags:
    - always

- name: Enable time synchronization (systemd)
  become: true
  ansible.builtin.systemd:
    name: systemd-timesyncd
    enabled: true
    state: started
  when: ansible_facts['system'] == "Linux"

- name: Set timezone (optional default)
  become: true
  community.general.timezone:
    name: "{{ system_timezone }}"
  when:
    - ansible_facts['system'] == "Linux"
    - system_timezone | length > 0

- name: Update packages
  ansible.builtin.include_tasks:
    file: "update/{{ 'darwin' if ansible_facts['system'] == 'Darwin' else ansible_facts['distribution'] | lower }}.yml"
  tags:
    - update

- name: Install packages
  include_role:
    name: common
    tasks_from: install
  tags:
    - packages

# Set fish sehll as the loging shell
- name: Get fish shell path
  ansible.builtin.command: which fish
  register: fish_path
  changed_when: false

- name: Ensure fish is registered as valid shell
  become: true
  ansible.builtin.lineinfile:
    path: /etc/shells
    line: "{{ fish_path.stdout }}"
    state: present
  when: ansible_facts['system'] == "Linux"

- name: Set fish as default shell
  become: true
  ansible.builtin.user:
    name: "{{ ansible_facts['user_id'] }}"
    shell: "{{ fish_path.stdout }}"
