- name: Gather facts
  ansible.builtin.setup:

- name: Resolve packages (shared logic)
  include_role:
    name: common
    tasks_from: resolve_packages
  tags:
    - packages

- name: Fail if OS installer missing
  ansible.builtin.stat:
    path: "{{ role_path }}/tasks/install/{{ ansible_platform }}.yml"
  register: installer
  vars:
    ansible_platform: "{{ 'darwin' if ansible_facts['system'] == 'Darwin' else ansible_facts['distribution'] | lower }}"

- ansible.builtin.fail:
    msg: "Unsupported Distribution: {{ ansible_facts['distribution'] }}"
  when: not installer.stat.exists

- name: Include OS installer
  include_tasks: "install/{{ ansible_platform }}.yml"
  vars:
    ansible_platform: "{{ 'darwin' if ansible_facts['system'] == 'Darwin' else ansible_facts['distribution'] | lower }}"
  tags:
    - packages
