# Terminal — truecolor + nerd font glyph support
set -g default-terminal "tmux-256color"
set -as terminal-overrides ",*:Tc"
set -as terminal-overrides ",*:UTF-8"
set -gq allow-passthrough on

# Prefix
set -g prefix C-a
unbind C-b
bind C-a send-prefix

# List of plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'fabioluciano/tmux-powerkit'
set -g @powerkit_plugins "datetime,battery,cpu,memory,git,hostname"

set -g @powerkit_theme "catppuccin"
set -g @powerkit_theme_variant "mocha"

# Choose your separator style
set -g @powerkit_separator_style "rounded"  # or normal, flame, pixel, honeycomb

# Enable spacing between elements
set -g @powerkit_elements_spacing "both"

# Customize update interval
set -g @powerkit_status_interval "5"

# Make it transparent
set -g @powerkit_transparent "true"

# Initialize TPM (keep this line at the very bottom)
run '~/.tmux/plugins/tpm/tpm'


